apiVersion: apps/v1
kind: Deployment
metadata:
  name: novostackprod-coll-55dac3628420459c8c719f910f503f41-depl
  labels:
    app: novostackprod-coll-55dac3628420459c8c719f910f503f41
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novostackprod-coll-55dac3628420459c8c719f910f503f41
  template:
    metadata:
      labels:
        app: novostackprod-coll-55dac3628420459c8c719f910f503f41
    spec:
      containers:
        - name: novostackprod-coll-55dac3628420459c8c719f910f503f41
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:novostackprod-coll-55dac3628420459c8c719f910f503f41
          imagePullPolicy: Always
          ports:
            - containerPort: 9030